sudo: false
language: python
env:
    - TESTENV=py27-django13
    - TESTENV=py27-django14
    - TESTENV=py27-django15
    - TESTENV=py27-django16
    - TESTENV=py27-django17
    - TESTENV=py27-django18
    - TESTENV=py34-django17
    - TESTENV=py34-django18

before_install:
    - pip install tox

script: tox -e $TESTENV

notifications:
  email: false
  irc: false
